DEBUG: true

GUI:
  ENABLED: true                 # Whether to enable the GUI (Only applies if VISUALIZE is false)
  UPDATE_RATE: 100              # GUI update rate in Hz (only applies if ENABLED is true)

UART:
  PORT: /dev/cu.usbmodem0E2208FC1
  BAUDRATE: 230400

QUBE:
  SIMULATION: false             # Whether to use MuJoCo simulation (true) or real hardware (false)
  VISUALIZE: true               # Whether to launch MuJoCo viewer (only applies if SIMULATION is true)
  SIMULATION_SPEED: 1.0         # 1.0 = real time, 0.5 = half speed

CONTROL:
  DT: 0.001                     # Control timestep [s] (1 kHz)
  DURATION: null                # Maximum simulation duration [s], set to null for unlimited
  MODERN_STABILIZATION: true    # Use modern stabilization method (true) or traditional method (false)
  
  # Voltage limits
  VOLTAGE_MAX: 3.0             # Maximum motor voltage [V]
  VOLTAGE_MIN: -3.0            # Minimum motor voltage [V]

PLANT:
  # Physical/simulation parameters (NOT CORRECT VALUES, MUST BE TUNED)
  MOTOR_CONSTANT: 0.05          # Motor torque constant [Nm/V]
  ARM_LENGTH: 0.085             # Distance from pivot to encoder axis [m]
  PENDULUM_LENGTH: 0.129        # Length of pendulum rod [m]
  ARM_MASS: 0.15                # Mass of arm [kg]
  PENDULUM_MASS: 0.05           # Mass of pendulum [kg]
  GRAVITY: 9.82                 # Gravitational acceleration [m/s^2]

DATA:
  LOGGING: true                 # Whether to log data for plotting
  PLOTTING: true                # Whether to enable plotting after simulation (Requires LOGGING to be true)
